server:
  ssl:
    key-store: classpath:local-ssl.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: local_ssl
    key-password: password
    enabled: true
  port: 8443

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://127.0.0.1:3306/yo_chatapp?useUnicode=yes&characterEncoding=UTF-8
    password: 123456qQ@


#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: 956227394363-pm783anre4tkrc73g2snpi3dkliut78m.apps.googleusercontent.com
#            client-secret: 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

security:
  jwt:
    token:
      secret-key: 111111
      expire-length: 86400000
      jwtCookieName: kichat